name: CI/CD backend Java to EKS

on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: us-east-1
  AWS_ROLE_ARN: arn:aws:iam::774305594396:role/github_role
  ECR_REPOSITORY: loja-virtual-notification-service
  EKS_CLUSTER: eks-loja-virtual-dev
  NAMESPACE: default

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write    # necess√°rio para OIDC
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build
        run: mvn clean package -DskipTests

      # ----------- assume role using oidc -----------
      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ env.AWS_ROLE_ARN }}

      # ----------- login ECR -----------
      - name: Login to Amazon ECR
        id: login
        uses: aws-actions/amazon-ecr-login@v2

      # ----------- docker build ----------
      - name: Build Docker image
        run: |
          docker build -t $ECR_REPOSITORY:latest .
          docker tag $ECR_REPOSITORY:latest ${{ steps.login.outputs.registry }}/${ECR_REPOSITORY}:latest

      - name: Push Docker image
        run: docker push ${{ steps.login.outputs.registry }}/${ECR_REPOSITORY}:latest

      # ----------- EKS config -----------
      - name: Configure kubectl (oidc-auth)
        run: |
          aws eks update-kubeconfig \
            --region $AWS_REGION \
            --name $EKS_CLUSTER

      - name: Update deployment
        run: |
          kubectl set image deployment/${ECR_REPOSITORY} \
            app=${{ steps.login.outputs.registry }}/${ECR_REPOSITORY}:latest \
            -n $NAMESPACE

      - name: Rollout status
        run: kubectl rollout status deployment/${ECR_REPOSITORY} -n $NAMESPACE
